README.md
Just a small clarification. Helps to avoid some problems and to keep consistency across all the users. However it's not crucial I think :)
=> Small clarification regarding time tracker installation

README.md
section 6.1. added, section 6.3 modified
=> Communication channels - modified

docs/Troubleshooting.md
This document adds the troubleshooting tips for various problems which may not be very frequent.
=> Add Troubleshooting document

README.md
removing 1 project description
=> Remove opensource slack channel from README.md

agreements.md
adding new agreement - opensource contributions
=> Add opensource section to agreements.md

agreements.md
=> review agreement update

README.md
updating open source contribution
=> updating open source contribution section

training.md
Adding link to article:
- Turn impostor syndrome into confidence: 15 tips for managers and individuals
- https://asana.com/pl/resources/impostor-syndrome
=> Adding article about imposter syndrome

training.md
The documentation system makes writing it easier.
It also facilitates conscious navigation through documentation, e.g. what to look for when we start with a new technology, and what we reach for as experts.
=> Add "The documentation system" article

training.md
Simon Sinek: The Problem Does Not Equal the Person + small formatting changes
=> Adding new video for leaders

README.md
Removing info about open source -> there is some information about it as S3 agreement.
=> Remove info about open source from README.md

README.md, agreements.md, remote_administrative_assistant.md, remote_assistant.md, time-tracking-how-to.md, training.md, travel.md
Semantic line breaks as automagically provided by https://github.com/bobheadxi/readable .
Tool itself requires some elbow grease to get it working, but IMO it is still easier to support it than develop one from scratch.
The tool basically builts on top of `remark` so some extra reformatting is done on top of semantic line breaks.
=> introducing semantic line breaks using `readable fmt **.md`

README.md
VirtualBox is not really working on Apple Silicon right now, so there's a suggestion for alternative virtualization platform
=> add recommendation for virtualization on Apple Silicon

.github/workflows/ci.yml, README.md, noxfile.py
We still want NOGIL to happen, but in the meanwhile we want to use 3.11 :)
=> drop no 3.10+ rule

agreements.md
=> HR circle explained

README.md, docs/Code_conventions.md
move & new convention addition are two distinct commits for easier review
=> new TODOs convention + move Conventions into separate file

agreements.md, remote_assistant.md, training.md
Changed all the files where trial word appears.
=> Trial period is now called evaulation period

README.md
this is not a complete nor even most up to date list, but its far closer to being up to date than what is currently in master
=> update project list

bin/rt_review_request.py
handy script for formulating message to be sent to `#review` channel.
IDK how to send slack message from the command line as the user, so for now it just copies the text into clipboard.
=> Review request script

agreements.md
=> Added notice periods section to agreements

README.md
=> sso is enough for 2fa

README.md
=> describe names-in-gh-handle rule
